### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by MBlaschek** [arnaudsm/raito#7]
Hi,

I would like to add a table of content to the website.
Do you know how this could be done?

Thanks again!
Ciao
Michael

**Comment by arnaudsm** [comment]
Hi, you need to create the table by hand in Markdown, with links. Just like `navbar.md`

I'm not considering to create an automated table of contents, since the front-end js can't scan the directory.
If you require server-side features like this, I'd recommend using something like [Jekyll](https://github.com/jekyll/jekyll)

**Comment by TomBraider42** [comment]
I think MBlaschek means links to the ids (headings) of the current page like `#juli-2021`.
But it doesn't work.
URL `http://localhost/raito/#/test#juli-2021` returns page not found.
